{% set version = "1.4.0" %}

package:
  name: pyevtk
  version: {{ version }}

source:
  url: https://github.com/pyscience-projects/pyevtk/archive/v{{ version }}.tar.gz
  sha256: 6225d3010ff2785945a93004cccdf04a48e99d8a759de4b8bed0529454698cc7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - pytest-runner

  run:
    - python >=3.6
    - numpy

test:
  requires:
    - pytest
  source_files:
    - examples/*.py
    - tests/*.py
  commands:
    - pytest tests/dummy.py
about:
  home: https://github.com/pyscience-projects/pyevtk
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: |
    EVTK (Export VTK) package allows exporting data to binary VTK files for
    visualization and data analysis with any of the visualization packages that
    support VTK files, e.g. Paraview, VisIt and Mayavi. EVTK does not depend on
    any external library (e.g. VTK), so it is easy to install in different
    systems.
  dev_url: https://github.com/paulo-herrera/PyEVTK

extra:
  recipe-maintainers:
    - renefritze
    - xylar
