{% set name = "pyevtk" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f6be7876a3a005c8258861551da4fe7e44ff1a2e7ff2a93d6dc51deedfda5f4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv 
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
    - setuptools
    - versioneer
    - pytest-runner

  run:
    - python >=3.6
    - numpy

test:
  requires:
    - pytest
  source_files:
    - examples/*.py
    - tests/*.py
  commands:
    - pytest tests/dummy.py
about:
  home: https://github.com/pyscience-projects/pyevtk
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: |
    EVTK (Export VTK) package allows exporting data to binary VTK files for
    visualization and data analysis with any of the visualization packages that
    support VTK files, e.g. Paraview, VisIt and Mayavi. EVTK does not depend on
    any external library (e.g. VTK), so it is easy to install in different
    systems.
  dev_url: https://github.com/paulo-herrera/PyEVTK

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49247
    reason: Dependency for gstools
  recipe-maintainers:
    - ianaobi
    - xylar
    - MuellerSeb
