travis:
  secure:
    BINSTAR_TOKEN: h1kpxIn4qFJ7oYenQjhGYw0kNA8UkhBC+CfM+UAVBZGA3t4u88m3QH0o2tadv8bZX136lTXAyWRVHRzVqy0zvkUHELYIPGkKwU6AwUBmp2Q/v0ND/qwhI9wTr0alCCz7dgU6P5ncAw4estGyYuBE5FkD5xfNqI+r0XHZMCXYJoevBUrFY66h4z1RYwfIgnt1BmZ8fNRxj/rJkmJin4EbEaLvT0MjOHsDUrsdFlUBLM/nQAO1VrpRoYlKwF1sPdeVFVu01Q4NhDBxCaZ5GRI3XxiU6FbaKSekD5FjRJ/uyW670ox1MDe8tUe2kIWm2Y/k4pOHae/QCpJzerCc1dlSMSRD/XwqL+BvtjGx4UPjXrH89O8X60Lvf6V++CXV5/TMOUVU+9ZlBk/V3Mn3NwiOt0YJ3T0Z53HaxKUKLVk/Qe5EE5sQTUP3jYFuLvNkgvz2vhFWprrCqndunCVii1nXlC7zsXCDD4RYa/+IWhVgXJk7vV7HN3iwqOYuY0OCV8+dCKyjDAKHBfrBtpHPXCQgZSkZ0KkHPWeji0qMRvGyoh/StjQfXMZwbiXpw8GDEK9EYEBgj8YiCIHZSHyjzhWifnjZDNO9si7Zje9TVuxKm4wMEEEkP3VpVUrwhhgeTmVphQrMgUQcZSo9JM1H6toSYDHCWiEzO/Fw1FO5n+jfRhw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
