travis:
  secure:
    BINSTAR_TOKEN: muKcmnuSp3xrD28fhKdu+ApeOnWl7AbG11KJqTHOlSxc4NsvWN5iqHs/gcN6Mi7qzDBycmLgnLRZkQS4gxHJEh9K19AtNEpIGbzUinIb/icQZCf2LB9ZYN2laFP33pOqCOfEbqhc+UR7NtZ+m4Xwadmsq5s5bwoXZdmGCQ9LzVNRVSHnbLISBCvL0ELg5XXA9jTpuRearhv5CIS/5MzpKEL9YosEFztNp6qFU1Xrv+Znn7FmSOc8Q+VK5485lOFp/iR8Zvopo+VXrRA18pMz7nnWk/tqyivGdgAxpv36wDG+PZLKWFZYHQt06ViQdI++2bzQ+Na1PcZ0qneAjgOhcWyHGRt49hqRi3QjokxNhJ0uUhV9j6gskwm6Hv+JAX9QFXzpIavdywkkE7CpY/yAhwKsjTqnZtCLwZNES++PRWFKi9xgbCmssyAgP9cjnnurbk5U/UsPcCCfPoNGJckQ6bmPPF8HRiDpk/LCB95P6QGJMIoDXooG9+B1cTo7k3m3sALHaNgLT7PEEQPjvivwgHEH2HJ2YkDINzLHhDlNGjeCR/Ekf0TZ0looZAayCaBoB5OdqnVXpd6A/Wa5tNM9sgMcnb8v8C55X4peRMBtc6cHSLfyDm0DTymrYtnpmogRgr1XgYabqkQlEb7qa0WbWXkApfBjFo4isHMo04Nq0iM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
