travis:
  secure:
    BINSTAR_TOKEN: TIlXJ2sLMev6iYwIZxbJLfCBCFchVwJken5AiNOvX2a5OeQiU5CTSRvJ59DnbtT28di2MN/jOcIHiH1g7f9OhRteo4V3vfPEnJeedeM6sdotc2OQK8GP4pl6eZcVl8o2Fefh8x8lTAaJYcNyhjoWqmjEl+yNFFmQc+ZRrXEh876eMbTsSB/rB8F21wH3pcnTuprg7jSuRVDxVyAP0wus3ZfZHlK+h1o0qJ2jPcRufr9gSAcCSNmiYnZTOkdjxRqawNuBw1gUevD4DKcxiiKdwJ/BFZNNF5xCnreN9G17U6+g7JSeI2NGxt/w4AAEaw3pV6FvyTBxfAmXRpMC7+ZtkNi8fQhXr2oS+2eEHRiXM2Kl9kEG0113FJWRd8RuLHMWPktN15D+e7yiF1y0sghjm40DKxbBB0h3yOpr8sQ4ZINlM1GPcmU/iDzNovk4X6i4joNJVaR0CexZMnI3dYTuQVTBVR2rLxc+kl1xspaT7W5GO8OAXAfKZeplSC9oHdaPRqr6K5m9iEFftr+zsBey0NjS4+M9+58JI2H4W1NlveBbcj9X5PCzoO3Z+9FeepfW2UsErCqXCYRGAZ8S+9nDL4tpGF1Tca22ywVfW0cNt3gOaItaYVpLVkeaF4ZV1c3/9/83NSrURixa0vm+rUGovEWiTLtPTBx/WSwr8F+TI0o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
